-- Create tables if they don't exist
CREATE TABLE IF NOT EXISTS fee_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_bn TEXT NOT NULL,
    description TEXT,
    is_default BOOLEAN DEFAULT false,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS for all fee related tables
ALTER TABLE fee_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE fee_structures ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_dues ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_waivers ENABLE ROW LEVEL SECURITY;

-- Create permissive policies for fee_types
DROP POLICY IF EXISTS "Enable all access for fee_types" ON fee_types;
CREATE POLICY "Enable all access for fee_types" ON fee_types FOR ALL USING (true) WITH CHECK (true);

-- Create permissive policies for fee_structures
DROP POLICY IF EXISTS "Enable all access for fee_structures" ON fee_structures;
CREATE POLICY "Enable all access for fee_structures" ON fee_structures FOR ALL USING (true) WITH CHECK (true);

-- Create permissive policies for student_dues
DROP POLICY IF EXISTS "Enable all access for student_dues" ON student_dues;
CREATE POLICY "Enable all access for student_dues" ON student_dues FOR ALL USING (true) WITH CHECK (true);

-- Create permissive policies for student_waivers
DROP POLICY IF EXISTS "Enable all access for student_waivers" ON student_waivers;
CREATE POLICY "Enable all access for student_waivers" ON student_waivers FOR ALL USING (true) WITH CHECK (true);
