-- Create home_sections table for dynamic homepage content
create table if not exists home_sections (
  id bigint generated by default as identity primary key,
  section_key text not null unique, -- 'director', 'about', 'mission_vision', 'departments'
  title text,
  subtitle text,
  content text, -- Rich text or long description
  image_url text,
  additional_data jsonb default '{}'::jsonb, -- For lists, extra fields
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert default data placeholders (Optional, avoids empty UI)
insert into home_sections (section_key, title, content, is_active)
values 
('director', 'পরিচালকের বাণী', 'এখানে পরিচালকের বাণী লিখুন...', true),
('about', 'আমাদের সম্পর্কে', 'মাদ্রাসা সম্পর্কে বিস্তারিত লিখুন...', true),
('mission_vision', 'লক্ষ্য ও উদ্দেশ্য', 'আমাদের লক্ষ্য ও উদ্দেশ্য...', true),
('departments', 'বিভাগসমূহ', 'আমাদের বিভাগসমূহ...', true)
on conflict (section_key) do nothing;

-- Enable RLS (Optional but recommended)
alter table home_sections enable row level security;

-- Policy: Allow read access to everyone
create policy "Enable read access for all users" on home_sections for select using (true);

-- Policy: Allow all access to authenticated users (admins)
create policy "Enable all access for authenticated users" on home_sections for all using (auth.role() = 'authenticated');
